
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import Header from "./components/header/Header";

import "bootstrap/dist/css/bootstrap.min.css";  
import Footer from "./components/footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider >
          <Header /> 
            {children}
          <Footer /> 
        </ThemeProvider>
      </body>
    </html>
  );
}




